stages:
    - Dockerfile_lint
    - tests
    - build
    - scan_image
    - deploy_dev
    - deploy_prod

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

.docker_login:
    before_script:
        - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

Dockerfile_lint:
    stage: Dockerfile_lint
    image: hadolint/hadolint:v2.14.0-alpine
    script:
        - hadolint --error 1 Dockerfile

pytest:
    stage: tests
    image: python:3.14.5-alpine3.23
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest
    cache:
        key: 
            files:
                - requirements.txt
        paths:
        - .cache/pip

build_image:
    extends: .docker_login
    stage: build
    script:
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

scan_image:
    stage: scan_image
    image: 
        name: aquasec/trivy
        entrypoint:
            - ""
    script:
        - trivy image -q --exit-code 1 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

.deploy:
    before_script:
        - apk add openssh-client-default=10.3p1
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

deploy_dev:
    stage: deploy_dev
    extends: .deploy
    needs: [build_image]
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
    image: alpine:3.22.4
    script:
        - chmod 0400 $PROD_SERVER_SSH_KEY && ssh-add $PROD_SERVER_SSH_KEY
        - ssh $DEV_SERVER echo "Hello world!"

deploy_prod:
    stage: deploy_prod
    extends: .deploy
    needs: [build_image]
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    image: alpine:3.22.4
    script:
        - chmod 0400 $PROD_SERVER_SSH_KEY && ssh-add $PROD_SERVER_SSH_KEY
        - ssh $PROD_SERVER echo "Hello world!"